"""Writes Railway/Route/Timetable50.csv: a bare test route with 50 stations, for the timetable
(scrolling, the touch timetable card), the map and the gradient chart (pitches, speed limits).

Built only from the Uchibo objects already in testcontent (OpenBVE's own open-source
compatibility objects). Drive it with Train/AndroidTest. Run: python make_timetable50.py
"""

STATIONS = 50
SPACING = 600          # metres between stations
FIRST = 300            # track position of the first station
DWELL = 30             # seconds stopped
RUN = 60               # seconds between stations


def clock(seconds):
    """OpenBVE's hh.mmss form."""
    h, rest = divmod(int(seconds), 3600)
    m, s = divmod(rest, 60)
    return "%d.%02d%02d" % (h, m, s)


lines = [
    "; Timetable test route: 50 stations, generated by make_timetable50.py - edit that, not this.",
    "; Only Uchibo objects (OpenBVE's open-source compatibility objects); drive with Train/AndroidTest.",
    "",
    "Options.UnitOfLength 1",
    "",
    "With Route",
    ".Comment Timetable test route: 50 stations",
    ".Gauge 1067",
    ".Timetable Timetable test",
    ".AmbientLight 160;160;160",
    ".DirectionalLight 255;255;255",
    ".LightDirection 60;-45",
    "",
    "With Structure",
    ".Rail(0) Uchibo\\Ballast.csv",
    ".Ground(0) Uchibo\\Grass.csv",
    ".FormL(0) Uchibo\\FormL.csv",
    ".FormR(0) Uchibo\\FormR.csv",
    ".FormCL(0) Uchibo\\FormCL.csv",
    ".FormCR(0) Uchibo\\FormCR.csv",
    "",
    "With Texture",
    ".Background(0) Uchibo\\Back_Mt.png",
    "",
    "With Track",
    "0, .Height 0.3, .Ground 0, .Back 0, .Section 0;2;4, .Limit 80",
]

events = {}


def add(position, text):
    events.setdefault(position, []).append(text)


start = 8 * 3600
for i in range(STATIONS):
    p = FIRST + i * SPACING
    arrive = start + i * (RUN + DWELL)
    depart = arrive + DWELL
    last = i == STATIONS - 1
    name = "Station %02d" % (i + 1)
    # A short platform on the left: 75 m either side of the station.
    for q in range(p - 75, p + 76, 25):
        add(q, ".Form 0;L;0;0")
    # Name; arrival; departure (none at the terminus); pass alarm; doors left.
    add(p, ".Sta %s;%s;%s;0;-1;;;;;;;;" % (name, "" if i == 0 else clock(arrive), "" if last else clock(depart)))
    add(p + 25, ".Stop 1")

# The gradient chart's material: a climb and a descent every few kilometres, and speed limits.
for k, pitch in enumerate([0, 12, 0, -8, 0, 20, 5, -15, 0, 10, 0]):
    add(1000 + k * 2700, ".Pitch %d" % pitch)
for k, limit in enumerate([80, 60, 90, 45, 70, 100, 50, 80]):
    add(2000 + k * 3600, ".Limit %d" % limit)
# A few curves, for the map.
for k, radius in enumerate([800, 0, -600, 0, 1000, 0, -900, 0]):
    add(1500 + k * 3700, ".Curve %d" % radius)

end = FIRST + STATIONS * SPACING
add(end, ".Height 0")
for position in sorted(events):
    lines.append("%d, %s" % (position, ", ".join(events[position])))
lines.append("%d, .Ground 0" % (end + 300))

open("Railway/Route/Timetable50.csv", "w", encoding="utf-8", newline="\r\n").write("\n".join(lines) + "\n")
print("wrote Railway/Route/Timetable50.csv:", STATIONS, "stations over", end, "m")
